/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_usp_larc_sembei_capacitysharing_crypto_CryptoProvider */

#ifndef _Included_br_usp_larc_sembei_capacitysharing_crypto_CryptoProvider
#define _Included_br_usp_larc_sembei_capacitysharing_crypto_CryptoProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_usp_larc_sembei_capacitysharing_crypto_CryptoProvider
 * Method:    benchKeyGen
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_br_usp_larc_sembei_capacitysharing_crypto_CryptoProvider_benchKeyGen
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
