/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_usp_larc_sembei_capacitysharing_crypto_MSS */

#ifndef _Included_br_usp_larc_sembei_capacitysharing_crypto_MSS
#define _Included_br_usp_larc_sembei_capacitysharing_crypto_MSS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_usp_larc_sembei_capacitysharing_crypto_MSS
 * Method:    keyGen
 * Signature: ([B)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_br_usp_larc_sembei_capacitysharing_crypto_MSS_keyGen
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     br_usp_larc_sembei_capacitysharing_crypto_MSS
 * Method:    sign
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_br_usp_larc_sembei_capacitysharing_crypto_MSS_sign
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     br_usp_larc_sembei_capacitysharing_crypto_MSS
 * Method:    verify
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_br_usp_larc_sembei_capacitysharing_crypto_MSS_verify
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
