/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_usp_larc_sembei_capacitysharing_crypto_util_FileManager */

#ifndef _Included_br_usp_larc_sembei_capacitysharing_crypto_util_FileManager
#define _Included_br_usp_larc_sembei_capacitysharing_crypto_util_FileManager
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
